---
- name: Install AWS CLI
  become: true
  apt:
    name: awscli
    update_cache: yes
    
- name: Ensures vagrant .aws dir exists
  file: path=~/.aws state=directory

- name: Create aws credentials
  shell: |
    aws configure set aws_access_key_id {{ workspace.aws.default.access_key_id }}
    aws configure set aws_secret_access_key {{ workspace.aws.default.secret_access_key }}
  
- name: Create aws default config
  shell: |
    aws configure set default.region {{ workspace.aws.default.region }}
    aws configure set default.output {{ workspace.aws.default.output }}
    
- name: Create aws config
  shell: |
    aws configure set source_profile default --profile {{ item.name }}
    aws configure set role_arn {{ item.role_arn }}
  loop: "{{ workspace.aws.profiles }}"
    