---
- name: check if nodejs already added
  stat:
    path: /opt/nodejs
  register: nodejs
  
- name: Create nodejs directory
  become: true
  file:
    path: /opt/nodejs
    state: directory
  when: nodejs.stat.exists == false

- name: Get nodejs tarball
  become: true
  unarchive:
    src: https://nodejs.org/dist/v12.18.3/node-v12.18.3-linux-x64.tar.gz
    dest: /opt/nodejs/
    remote_src: yes
  when: nodejs.stat.exists == false
  
- name: Remove nodejs tarball
  file:
    path: node-v12.18.3-linux-x64.tar.gz
    state: absent
  when: nodejs.stat.exists == false

- name: Link nodejs
  become: true
  register: link_result
  shell: |
    cd /opt/nodejs
    mv node-v12.18.3-linux-x64 12.18.3
    ln -s 12.18.3 current
    ln -s /opt/nodejs/current/bin/node /bin/node
  failed_when:
    - link_result.rc > 0
    - "'File exists' not in link_result.stderr"
  changed_when: link_result.rc == 0
  
- name: Get node version
  shell: node --version
  register: node_version
  
- name: Print node version
  debug:
    msg: "Nodejs Version: {{ node_version.stdout }}"
  
- name: Install NVM
  become_user: vagrant
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
