---
- hosts:  "{{ node_name }}"
  become: false
  tasks:
    - name: Install pexpect
      become: true
      apt:
        name: python3-pexpect
        state: present
        update_cache: yes

    - name: Setup Java
      when: workspace.java.enabled
      become: true
      import_tasks: tasks/java.yml

    - name: Setup Docker
      when: workspace.docker.enabled
      become: true
      import_tasks: tasks/docker.yml

    - name: Setup AWS CLI
      when: workspace.aws.enabled
      import_tasks: tasks/aws.yml

    - name: Setup Nodejs
      when: workspace.node.enabled
      import_tasks: tasks/nodejs.yml

    - name: Setup Yarn
      when: workspace.yarn.enabled
      become: true
      import_tasks: tasks/yarn.yml

    - name: Setup Terraform
      when: workspace.terraform.enabled
      become: true
      import_tasks: tasks/terraform.yml