---
- hosts:  "{{ node_name }}"
  become: false
  tasks:
    - name: Install pexpect
      become: true
      apt:
        name: python3-pexpect
        state: present
        update_cache: yes

    - name: Setup Go
      when: workspace.go.enabled
      become: true
      import_tasks: tasks/go.yml

    - name: Setup jq
      become: true
      import_tasks: tasks/jq.yml
      
    - name: Setup pip
      become: true
      import_tasks: tasks/pip.yml

    - name: Setup pup
      become: true
      import_tasks: tasks/pup.yml

    - name: Setup Docker
      become: true
      import_tasks: tasks/docker.yml
      
    - name: Setup Java
      when: workspace.java.enabled
      become: true
      import_tasks: tasks/java.yml

    - name: Setup AWS CLI
      when: workspace.aws.enabled
      import_tasks: tasks/aws.yml

    - name: Setup Nodejs
      when: workspace.node.enabled
      import_tasks: tasks/nodejs.yml

    - name: Setup Yarn
      when: workspace.yarn.enabled
      become: true
      import_tasks: tasks/yarn.yml

    - name: Setup Terraform
      when: workspace.terraform.enabled
      become: true
      import_tasks: tasks/terraform.yml
      
    - name: Setup Ngrok
      when: workspace.ngrok.enabled
      become: true
      import_tasks: tasks/ngrok.yml
